model_type: autoreg
dataset: wd-articles
d_model: 512
d_latent: 128
n_heads: 8
n_layers: 6

batch_size: 16
learning_rate: 0.0001
num_epochs: 3
shuffle_train: false
use_padding: true

verify_every: 10

beta0: 0.1
beta1: 1.0

num_diversity_samples: 100
num_generated_test_graphs: 1000
num_generated_latent_graphs: 1000

beam_width: 4
lr_scheduler: true
save_every: 5
sample_frac: 0.1
resume_from_checkpoint: false
checkpoint_path: checkpoints/autoreg_wd_articles.pt

experiment_name: autoreg_vae_wd_articles

use_test_for_final_eval: false  