model_type: autoreg
dataset: syn-types
d_model: 512
d_latent: 24
n_heads: 4
n_layers: 3

batch_size: 256
learning_rate: 0.0001
num_epochs: 51
shuffle_train: true
use_padding: false

verify_every: 10

beta0: 0.1
beta1: 1.0

num_diversity_samples: 10000
num_generated_test_graphs: 1000
num_generated_latent_graphs: 1000

beam_width: 4
lr_scheduler: true
save_every: 5
sample_frac: 0.1
resume_from_checkpoint: false
checkpoint_path: checkpoints/autoreg_syn_types.pt

experiment_name: autoreg_vae_syn_types

use_test_for_final_eval: false  