# DENSE scoring mode

# Model architecture
d_model: 768
d_latent: 768
n_layers: 3
n_heads: 12
d_ff: 3072
dropout: 0.1

# Training parameters
batch_size: 512
learning_rate: 0.0005
num_epochs: 1000
beta: 0.0001           # Lower KL weight for dense mode (more complex distributions)
gamma: 0.5             # Lower entity weight (dense mode focuses on all edges)
zeta: 1.0              # Standard edge weight (dense scores all possible edges)

# Dataset parameters
dataset: syn-paths
max_nodes: 4
max_edges: 3

# Sampling parameters
sampling_method: probabilistic
sampling_temperature: 0.8  # Slightly lower temperature for more deterministic sampling

# Optimization settings
lr_scheduler: true
save_every: 50

# Experiment tracking
experiment_name: rescal_vae_syn_paths_dense_a100
verify_every: 25
verify_samples: 10000

# Evaluation settings
use_test_for_final_eval: false

# Compression bits calculation - DENSE MODE
compression_scoring_mode: dense
compression_log_every: 10
