# SPARSE scoring mode

# Model architecture
model_type: rescal_vae
d_model: 768
d_latent: 768
n_layers: 3
n_heads: 12
d_ff: 3072
dropout: 0.1

# Training parameters
batch_size: 4096
learning_rate: 0.001
num_epochs: 800
beta: 0.001            # KL divergence weight (low for better reconstruction)
gamma: 1.0             # Entity loss weight
zeta: 10.0             # Edge reconstruction loss weight (high priority on edges)

# Dataset parameters
dataset: syn-paths
max_nodes: 4
max_edges: 3

# Sampling parameters
sampling_method: probabilistic
sampling_temperature: 1.0

# Optimization settings
lr_scheduler: true
save_every: 25

# Experiment tracking
experiment_name: rescal_vae_syn_paths_sparse_a100
verify_every: 20
verify_samples: 20000

# Evaluation settings
use_test_for_final_eval: false

# Compression bits calculation - SPARSE MODE
compression_scoring_mode: sparse
compression_log_every: 10
