# Model architecture
model_type: rescal_vae
d_model: 512
d_latent: 512
n_layers: 2
n_heads: 8
d_ff: 2048
dropout: 0.1

# Training parameters
batch_size: 1024
learning_rate: 0.0005
num_epochs: 1300
beta: 0.001      # KL divergence weight
gamma: 1.0       # Entity loss weight
zeta: 10.0       # Edge reconstruction loss weight

# Dataset parameters
dataset: syn-paths
max_nodes: 4
max_edges: 3

# Sampling parameters
sampling_method: probabilistic  # Options: probabilistic (default), deterministic
sampling_temperature: 1.0       # Temperature for probabilistic sampling (higher = more random)

lr_scheduler: true
save_every: 50

experiment_name: rescal_vae_syn_paths
verify_every: 25  # Verify generated graphs every 25 epochs
verify_samples: 10000  # Number of samples to verify

# Evaluation settings
use_test_for_final_eval: false  # If true, uses test set for final evaluation (WARNING: only for final runs!)

# Compression bits estimation
compression_scoring_mode: sparse  # Options: sparse (default, only edges observed), dense (full graph)
compression_log_every: 10  # Compute and log compression bits every N epochs