encoder_type: transformer
decoder_type: transformer
d_model: 512
d_hidden: 512
d_latent: 512
n_layers: 2
n_heads: 8
d_ff: 2048
dropout: 0.1

batch_size: 1024
learning_rate: 0.0005
num_epochs: 1300
beta: 0.0000001
gamma: 100.0
zeta: 1.0

dataset: syn-types
max_nodes: 10
max_edges: 9

lr_scheduler: true
save_every: 50
num_workers: 4

experiment_name: kgvae_syn_types_transformer
verify_every: 25  # Verify generated graphs every 25 epochs
verify_samples: 10000  # Number of samples to verify